#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-openhtmltopdf-parent
Version  : 0.0.1.rc9
Release  : 3
URL      : https://github.com/danfickle/openhtmltopdf/archive/openhtmltopdf-parent-0.0.1-RC9.tar.gz
Source0  : https://github.com/danfickle/openhtmltopdf/archive/openhtmltopdf-parent-0.0.1-RC9.tar.gz
Source1  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9/openhtmltopdf-core-0.0.1-RC9.jar
Source2  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9/openhtmltopdf-core-0.0.1-RC9.pom
Source3  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9/openhtmltopdf-jsoup-dom-converter-0.0.1-RC9.jar
Source4  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9/openhtmltopdf-jsoup-dom-converter-0.0.1-RC9.pom
Source5  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-parent/0.0.1-RC9/openhtmltopdf-parent-0.0.1-RC9.pom
Source6  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9/openhtmltopdf-pdfbox-0.0.1-RC9.jar
Source7  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9/openhtmltopdf-pdfbox-0.0.1-RC9.pom
Source8  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9/openhtmltopdf-rtl-support-0.0.1-RC9.jar
Source9  : https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9/openhtmltopdf-rtl-support-0.0.1-RC9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 LGPL-3.0 W3C
Requires: mvn-openhtmltopdf-parent-data = %{version}-%{release}

%description
XML Entity Declarations for Characters
The character entity sets distributed with DocBook XML are direct
copies of the official entities located at

%package data
Summary: data components for the mvn-openhtmltopdf-parent package.
Group: Data

%description data
data components for the mvn-openhtmltopdf-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-parent/0.0.1-RC9
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-parent/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9/openhtmltopdf-core-0.0.1-RC9.jar
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC9/openhtmltopdf-core-0.0.1-RC9.pom
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9/openhtmltopdf-jsoup-dom-converter-0.0.1-RC9.jar
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/0.0.1-RC9/openhtmltopdf-jsoup-dom-converter-0.0.1-RC9.pom
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-parent/0.0.1-RC9/openhtmltopdf-parent-0.0.1-RC9.pom
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9/openhtmltopdf-pdfbox-0.0.1-RC9.jar
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/0.0.1-RC9/openhtmltopdf-pdfbox-0.0.1-RC9.pom
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9/openhtmltopdf-rtl-support-0.0.1-RC9.jar
/usr/share/java/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/0.0.1-RC9/openhtmltopdf-rtl-support-0.0.1-RC9.pom
